# Generated by Django 5.2.8 on 2025-11-08 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appInmuebles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('duracion_meses', models.IntegerField(help_text='Duración en meses')),
                ('valor_arriendo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_administracion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposito_garantia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_pago', models.IntegerField(default=1, help_text='Día del mes para el pago')),
                ('porcentaje_incremento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de incremento anual', max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('documento_contrato_url', models.URLField(blank=True, help_text='URL del contrato PDF', null=True)),
                ('clausulas_especiales', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='appInmuebles.inmueble')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_inquilino', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_propietario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RenovacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renovacion', models.DateField(auto_now_add=True)),
                ('nuevo_valor_arriendo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('contrato_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovacion_de', to='appContratos.contrato')),
                ('contrato_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='appContratos.contrato')),
            ],
            options={
                'verbose_name': 'Renovación de Contrato',
                'verbose_name_plural': 'Renovaciones de Contratos',
                'db_table': 'renovaciones_contratos',
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado', 'fecha_fin'], name='contratos_estado_9aa255_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['inquilino'], name='contratos_inquili_c3fd18_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['inmueble'], name='contratos_inmuebl_1ef17a_idx'),
        ),
    ]
