# Generated by Django 5.2.8 on 2025-11-08 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appContratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=50, unique=True)),
                ('concepto', models.CharField(choices=[('arriendo', 'Arriendo'), ('administracion', 'Administración'), ('servicios', 'Servicios'), ('mora', 'Mora'), ('reparacion', 'Reparación'), ('otro', 'Otro')], default='arriendo', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('periodo_inicio', models.DateField(help_text='Inicio del período facturado')),
                ('periodo_fin', models.DateField(help_text='Fin del período facturado')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_mora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_mora', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=20)),
                ('documento_url', models.URLField(blank=True, help_text='URL del PDF de cuenta de cobro', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='appContratos.contrato')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta de Cobro',
                'verbose_name_plural': 'Cuentas de Cobro',
                'db_table': 'cuentas_cobro',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.IntegerField()),
                ('periodo_ano', models.IntegerField()),
                ('total_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_mora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('documento_url', models.URLField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados_cuenta', to='appContratos.contrato')),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta',
                'db_table': 'estados_cuenta',
                'ordering': ['-periodo_ano', '-periodo_mes'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.CharField(max_length=50, unique=True)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('cheque', 'Cheque'), ('pse', 'PSE'), ('otro', 'Otro')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia_bancaria', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('comprobante_url', models.URLField(blank=True, help_text='URL del comprobante de pago', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_cobro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='appPagos.cuentacobro')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddIndex(
            model_name='cuentacobro',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='cuentas_cob_estado_74aff0_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacobro',
            index=models.Index(fields=['contrato'], name='cuentas_cob_contrat_69e9a7_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentacobro',
            index=models.Index(fields=['inquilino'], name='cuentas_cob_inquili_500a17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estadocuenta',
            unique_together={('contrato', 'periodo_mes', 'periodo_ano')},
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estado', 'fecha_pago'], name='pagos_estado_8a4f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['cuenta_cobro'], name='pagos_cuenta__2cd308_idx'),
        ),
    ]
