# Generated by Django 5.2.8 on 2025-11-08 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_pagos', models.BooleanField(default=True, verbose_name='Notificaciones de pagos')),
                ('notif_contratos', models.BooleanField(default=True, verbose_name='Notificaciones de contratos')),
                ('notif_mantenimiento', models.BooleanField(default=True, verbose_name='Notificaciones de mantenimiento')),
                ('notif_recordatorios', models.BooleanField(default=True, verbose_name='Recordatorios')),
                ('notif_email', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('notif_push', models.BooleanField(default=True, verbose_name='Notificaciones push')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'db_table': 'configuraciones_notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('advertencia', 'Advertencia'), ('urgente', 'Urgente'), ('recordatorio', 'Recordatorio'), ('pago', 'Pago'), ('contrato', 'Contrato'), ('mantenimiento', 'Mantenimiento')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('url', models.URLField(blank=True, help_text='URL relacionada con la notificación', null=True)),
                ('referencia_tipo', models.CharField(blank=True, help_text='Tipo de objeto relacionado (contrato, pago, etc.)', max_length=50, null=True)),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID del objeto relacionado', null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_ef49b7_idx'), models.Index(fields=['tipo'], name='notificacio_tipo_f5d897_idx')],
            },
        ),
    ]
