# Generated by Django 5.2.8 on 2025-11-08 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appContratos', '0001_initial'),
        ('appInmuebles', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('pintura', 'Pintura'), ('carpinteria', 'Carpintería'), ('electrodomesticos', 'Electrodomésticos'), ('limpieza', 'Limpieza'), ('jardineria', 'Jardinería'), ('cerrajeria', 'Cerrajería'), ('aire_acondicionado', 'Aire Acondicionado'), ('otro', 'Otro')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_especifica', models.CharField(blank=True, help_text='Ej: Baño principal, Cocina, Sala, etc.', max_length=200, null=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fotos', models.JSONField(blank=True, default=list, help_text='URLs de fotos del problema')),
                ('documentos', models.JSONField(blank=True, default=list, help_text='URLs de documentos relacionados')),
                ('observaciones_solicitante', models.TextField(blank=True, null=True)),
                ('observaciones_tecnico', models.TextField(blank=True, null=True)),
                ('solucion_aplicada', models.TextField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, help_text='Calificación del servicio (1-5)', null=True)),
                ('comentario_calificacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_asignados', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_mantenimiento', to='appContratos.contrato')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_mantenimiento', to='appInmuebles.inmueble')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_mantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Mantenimiento',
                'verbose_name_plural': 'Solicitudes de Mantenimiento',
                'db_table': 'solicitudes_mantenimiento',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fotos', models.JSONField(blank=True, default=list, help_text='URLs de fotos del seguimiento')),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='appMantenimiento.solicitudmantenimiento')),
            ],
            options={
                'verbose_name': 'Seguimiento de Mantenimiento',
                'verbose_name_plural': 'Seguimientos de Mantenimiento',
                'db_table': 'seguimientos_mantenimiento',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudmantenimiento',
            index=models.Index(fields=['estado', 'prioridad'], name='solicitudes_estado_691e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudmantenimiento',
            index=models.Index(fields=['inmueble'], name='solicitudes_inmuebl_59b915_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudmantenimiento',
            index=models.Index(fields=['solicitante'], name='solicitudes_solicit_56c3af_idx'),
        ),
    ]
