# Generated by Django 5.2.8 on 2025-11-05 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('terreno', 'Terreno'), ('casa', 'Casa'), ('apartamento', 'Apartamento'), ('local_comercial', 'Local Comercial'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('otro', 'Otro')], max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Inmueble',
                'verbose_name_plural': 'Categorías de Inmuebles',
                'db_table': 'categorias_inmuebles',
            },
        ),
        migrations.CreateModel(
            name='MuebleInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=50)),
                ('foto', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mueble de Inmueble',
                'verbose_name_plural': 'Muebles de Inmuebles',
                'db_table': 'muebles_inmuebles',
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('area_construida', models.DecimalField(decimal_places=2, help_text='Metros cuadrados', max_digits=10)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, help_text='Metros cuadrados', max_digits=10, null=True)),
                ('num_habitaciones', models.IntegerField(default=0)),
                ('num_banos', models.IntegerField(default=0)),
                ('num_parqueaderos', models.IntegerField(default=0)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('precio_arriendo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_administracion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposito_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amoblado', models.BooleanField(default=False)),
                ('permite_mascotas', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('mantenimiento', 'En Mantenimiento'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20)),
                ('fotos', models.JSONField(blank=True, default=list, help_text='URLs de las fotos')),
                ('caracteristicas', models.JSONField(blank=True, default=dict, help_text='Características adicionales')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inmuebles', to='appInmuebles.categoriainmueble')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'db_table': 'inmuebles',
                'ordering': ['-creado_en'],
            },
        ),
    ]
