# Generated by Django 5.2.8 on 2025-11-05 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appInmuebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='muebleinmueble',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muebles', to='appInmuebles.inmueble'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['estado', 'ciudad'], name='inmuebles_estado_17b34b_idx'),
        ),
        migrations.AddIndex(
            model_name='inmueble',
            index=models.Index(fields=['propietario'], name='inmuebles_propiet_2f49b9_idx'),
        ),
    ]
