# Generated by Django 5.2.8 on 2025-11-10 12:55

import appUploads.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=appUploads.models.upload_to)),
                ('nombre_original', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('foto_perfil', 'Foto de Perfil'), ('foto_inmueble', 'Foto de Inmueble'), ('foto_mantenimiento', 'Foto de Mantenimiento'), ('documento_contrato', 'Documento de Contrato'), ('comprobante_pago', 'Comprobante de Pago'), ('otro', 'Otro')], max_length=50)),
                ('tamano', models.IntegerField(help_text='Tamaño en bytes')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
